### ISSUE TITLE
Loading spinner remains forever (regression)

### ISSUE THREAD

**Issue by jaens** [astral-sh/ruff-vscode#609]
After opening a project / Python file, the Ruff spinner in the VSCode status bar keeps spinning forever.

![image](https://github.com/user-attachments/assets/3ebed0bf-7b0b-4913-8628-7aaa73412bd6)

This is a regression in v2024.44, the same behaviour does not happen in v2024.42.

Logs do not show anything interesting:
```log
2024-09-09 20:00:21.373 [info] Name: Ruff
2024-09-09 20:00:21.373 [info] Module: ruff
2024-09-09 20:00:21.373 [info] Python extension loading
2024-09-09 20:00:21.373 [info] Waiting for interpreter from python extension.
2024-09-09 20:00:21.373 [info] Python extension loaded
2024-09-09 20:00:21.373 [info] Using interpreter: /project/.direnv/python-3.10.15/bin/python
2024-09-09 20:00:21.373 [info] Using the Ruff binary: /home/user/.local/bin/ruff
2024-09-09 20:00:21.381 [info] Resolved 'ruff.nativeServer: auto' to use the native server
2024-09-09 20:00:21.382 [info] Found Ruff 0.6.4 at /home/user/.local/bin/ruff
2024-09-09 20:00:21.382 [info] Server run command: /home/user/.local/bin/ruff server
2024-09-09 20:00:21.382 [info] Server: Start requested.
2024-09-09 20:00:21.388 [info] [Trace - 8:00:21 PM] Sending request 'initialize - (0)'.
2024-09-09 20:00:21.404 [info] [Trace - 8:00:21 PM] Received response 'initialize - (0)' in 16ms.
2024-09-09 20:00:21.404 [info] [Trace - 8:00:21 PM] Sending notification 'initialized'.
2024-09-09 20:00:21.412 [info] [Trace - 8:00:21 PM] Sending notification 'textDocument/didOpen'.
2024-09-09 20:00:21.412 [info] [Trace - 8:00:21 PM] Sending request 'textDocument/diagnostic - (1)'.
2024-09-09 20:00:21.418 [info] warning: `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible. Ignoring `one-blank-line-before-class`.

2024-09-09 20:00:21.421 [info] [Trace - 8:00:21 PM] Received request 'client/registerCapability - (1)'.
2024-09-09 20:00:21.421 [info] [Trace - 8:00:21 PM] Sending response 'client/registerCapability - (1)'. Processing request took 0ms
2024-09-09 20:00:21.421 [info] [Trace - 8:00:21 PM] Received response 'textDocument/diagnostic - (1)' in 9ms.
2024-09-09 20:00:21.425 [info] [Trace - 8:00:21 PM]    0.010575545s  INFO ruff:main ruff_server::server: Configuration file watcher successfully registered

2024-09-09 20:00:21.463 [info] [Trace - 8:00:21 PM] Sending request 'textDocument/codeAction - (2)'.
2024-09-09 20:00:21.465 [info] [Trace - 8:00:21 PM] Received response 'textDocument/codeAction - (2)' in 2ms.
```

**Comment by dhruvmanila** [comment]
Thanks for the report. That's fixed on main, I'll make a release to get it out.

**Comment by maphew** [comment]
I have the same issue. My version number doesn't match either of the ones noted above, so maybe it's not the same?

Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

log:

2024-09-09 13:12:07.479 [info] Name: Ruff
2024-09-09 13:12:07.479 [info] Module: ruff
2024-09-09 13:12:07.479 [info] Python extension loading
2024-09-09 13:12:07.479 [info] Waiting for interpreter from python extension.
2024-09-09 13:12:07.479 [info] Python extension loaded
2024-09-09 13:12:07.479 [info] Using interpreter: d:\personal\fweb\.pixi\envs\default\python.exe
2024-09-09 13:12:09.493 [info] Falling back to bundled executable: c:\Users\mhwilkie\.vscode\extensions\charliermarsh.ruff-2024.44.0-win32-x64\bundled\libs\bin\ruff.exe
2024-09-09 13:12:09.917 [info] Resolved 'ruff.nativeServer: auto' to use the native server
2024-09-09 13:12:09.919 [info] Found Ruff 0.6.4 at c:\Users\mhwilkie\.vscode\extensions\charliermarsh.ruff-2024.44.0-win32-x64\bundled\libs\bin\ruff.exe
2024-09-09 13:12:09.919 [info] Server run command: c:\Users\mhwilkie\.vscode\extensions\charliermarsh.ruff-2024.44.0-win32-x64\bundled\libs\bin\ruff.exe server
2024-09-09 13:12:09.919 [info] Server: Start requested.

**Comment by gameliee** [comment]
I have the same problem @maphew , have you managed to fix it?

**Comment by dhruvmanila** [comment]
@gameliee @maphew It should be fixed in the latest release which should be out in ~15 minutes.

**Comment by gameliee** [comment]
@dhruvmanila thank you, way faster than I expected, great work

**Comment by chrisk314** [comment]
@dhruvmanila I'm still seeing this same issue and I'm on the latest version 2024.48.0. This started happening a couple of weeks ago without any changes to my vs code settings. I'm on auto update, so I guess an update caused this. My issue is slightly different in that I don't see any requests going to the ruff server.  I've tried with `ruff.nativeServer` set to `on`, `off`, and `auto`. This is all I get in the ruff logs. Note that this issue is not limited to `pyenv` virtualenvs. Seeing this with all my environments. I've tried uninstalling the extension and reinstalling. I've added trace logging with `"ruff.trace.server": "messages"` and it doesn't show anything else in the logs.
```txt
2024-09-19 20:57:24.113 [info] Name: Ruff
2024-09-19 20:57:24.113 [info] Module: ruff
2024-09-19 20:57:24.113 [info] Python extension loading
2024-09-19 20:57:24.113 [info] Waiting for interpreter from python extension.
2024-09-19 20:57:24.574 [info] Python extension loaded
2024-09-19 20:57:24.900 [info] Using interpreter: /home/csk/.pyenv/versions/plugboard-3.12/bin/python
```

**Comment by MichaReiser** [comment]
@chrisk314 this seems different. Would you mind opening a new issue and sharing your ruff VS code configuration? You may also want to try setting `"ruff.trace.server": "verbose"`. Maybe we then see a few more messages in the output panel.

**Comment by chrisk314** [comment]
@MichaReiser I've opened a new issue for my specific problem as requested here #619. Thanks for your help.
